"ui.background" = { bg = "base1" }
"ui.bufferline" = { fg = "subtext0", bg = "base1" }
"ui.bufferline.active" = { fg = "cursor", bg = "base2", underline = { color = "cursor", style = "line" } }
"ui.bufferline.background" = { bg = "base0" }
"ui.text" = "text"
"ui.text.focus" = { fg = "magenta0", bg = "surface0" }

[palette]
cursor = "#f2cddc"
base0 = ""
base1 = ""
base2 = ""
surface0 = ""
surface1 = ""
text0 = ""
text1 = ""
text2 = ""
red0 = ""
red1 = ""
yellow0 = ""
yellow1 = ""
green0 = ""
green1 = ""
cyan0 = ""
cyan1 = ""
blue0 = ""
blue1 = ""
magenta0 = ""
magenta1 = ""
